#243 urls reduced to 239(5 blanks).
#239 urls reduced to 216 after removing duplicates.

urls = [
    # Miscellaneous
    # this is a survey {"url": "https://adoption.microsoft.com/en-us/ai-readiness-wizard/", "source": "adoption.microsoft.com"},
    {"url": "https://blogs.microsoft.com/blog/2024/10/21/new-autonomous-agents-scale-your-team-like-never-before/", "source": "blogs.microsoft.com"},
    {"url": "https://blogs.microsoft.com/blog/2024/11/12/https-blogs-microsoft-com-blog-2024-11-12-how-real-world-businesses-are-transforming-with-ai/", "source": "blogs.microsoft.com"},
    {"url": "https://blogs.microsoft.com/blog/2024/11/12/idcs-2024-ai-opportunity-study-top-five-ai-trends-to-watch/", "source": "blogs.microsoft.com"},
    # This is a PDF{"url": "https://msft.it/6049UDDsU", "source": "msft.it"},
    {"url": "https://podcast.beyondtheprompt.ai/episodes/practical-strategies-for-leveraging-ai-in-your-business-wharton-professor-ethan-mollick", "source": "podcast.beyondtheprompt.ai"},
    {"url": "https://ukstories.microsoft.com/features/barnsley-council-releasing-the-potential-with-microsoft-copilot/", "source": "ukstories.microsoft.com"},
    {"url": "https://ukstories.microsoft.com/features/how-virgin-atlantic-is-flying-higher-with-copilot/", "source": "ukstories.microsoft.com"},
    #This is a video {"url": "https://www.goodmorningamerica.com/news/video/microsoft-linkedin-talk-ai-workplace-110018966", "source": "www.goodmorningamerica.com"},
    {"url": "https://www.microsoft.com/en-us/microsoft-365/blog/2024/09/16/microsoft-365-copilot-wave-2-pages-python-in-excel-and-agents/", "source": "www.microsoft.com"},
    {"url": "https://www.microsoft.com/en-us/microsoft-365/blog/2024/11/19/introducing-copilot-actions-new-agents-and-tools-to-empower-it-teams/", "source": "www.microsoft.com"},
    {"url": "https://www.microsoft.com/en/customers/story/1703814256939529124-volvo-group-automotive-azure-ai-services", "source": "www.microsoft.com"},
    # Duplicate url is in Microsoft Customer Case Studies {"url": "https://www.microsoft.com/en/customers/story/19404-clifford-chance-microsoft-365-copilot", "source": "www.microsoft.com"},

    # LinkedIn Business PDFs - PDF is not a valid URL
    #{"url": "https://business.linkedin.com/content/dam/business/marketing-solutions/global/en_US/site/pdf/infographics/2024-marketing-jobs-outlook.pdf?src=bl-po", "source": "business.linkedin.com/pdf"},

    # LinkedIn Business
    {"url": "https://business.linkedin.com/talent-solutions/global-talent-trends", "source": "business.linkedin.com"},

    # Microsoft Customers (Case Studies)
    {"url": "https://customers.microsoft.com/en-gb/story/1770536569687978092-visier-solutions-azure-openai-service-professional-services-en-canada", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-gb/story/1782421038868081701-maire-microsoft-teams-energy-en-italy", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-gb/story/1790119689031635867-trace3-microsoft-365-professional-services-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-gb/story/1790435165492425096-eon-se-microsoft-copilot-for-microsoft-365-energy-en-germany", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-gb/story/1802017730982552224-uniper-se-microsoft-copilot-for-microsoft-365-energy-en-germany", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-gb/story/1802756598954587083-access-holdings-plc-microsoft-365-banking-and-capital-markets-en-nigeria", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-gb/story/1804597267941884304-baptistcare-sharepoint-nonprofit-en-australia", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-gb/story/1804968308500747501-sultan-microsoft-copilot-health-provider-en-kuwait", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-gb/story/1805001416118108722-teladochealth-power-apps-health-provider-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-gb/story/1815128464686923048-aztec-group-microsoft-365-copilot-banking-and-capital-markets-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-gb/story/1816271784634453515-four-agency-microsoft-365-copilot-professional-services-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1735001154382665808-sasfin-bank-azure-banking-en-south-africa", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1740058425924206437-telstra-telecommunications-azure-openai-service", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1744450394922857891-onepoint-github-copilot-professional-services-en-france", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1744468024452864249-kantar-windows-11-professional-services-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1749403583645228440-amadeus-microsoft-365-professional-services-en-france", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1749522406496386350-kpmg-microsoft-365-copilot-professional-services-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1749886282579475320-mcdonalds-china-azure-retailers-en-china", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1754582924902623921-adobe-inc-azure-retailers-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1758695276753608190-petrobras-azure-openai-service-energy-en-brazil", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1758915282906956032-scottishwater-microsoft-copilot-energy-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1759188982673652446-o2-microsoft-365-telecommunications-en-czech-republic", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1759306888687672662-morulahealth-microsoft-365-business-premium-health-provider-en-united-kigdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1759309014350031747-joos-microsoft-copilot-consumer-goods-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1759333055842391656-topsoe-azure-openai-service-discrete-manufacturing-en-denmark", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1760377839901581759-axa-gie-azure-insurance-en-france", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1762150085964970175-enerjisa-uretim-microsoft-copilot-energy-en-turkiye", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1768027434711024743-shrinerschildrens-azure-health-provider-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1770472924267393932-motor-oil-group-microsoft-365-energy-en-greece", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1772120481217819586-unumgroup-azure-insurance-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1772353582649569700-ocgoodwill-azure-ai-services-nonprofit-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1774095788906881160-orange-azure-openai-service-telecommunications-en-france", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1776965075841351020-petrochemical-industries-company-microsoft-365-energy-en-kuwait", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1783172439597920946-absa-github-copilot-banking-and-capital-markets-en-south-africa", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1785448033474736158-sandvik-coromant-microsoft-copilot-for-sales-discrete-manufacturing-en-sweden", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1790507377097905834-paconsulting-dynamics-365-sales-professional-services-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1792966154673709027-nagel-group-azure-openai-service-travel-and-transportation-en-germany", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1794442287816192713-asahi-europe-and-international-microsoft-copilot-for-microsoft-365-consumer-goods-en-czechia", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1795477416065405316-epam-systems-microsoft-copilot-for-microsoft-365-professional-services-en-hungary", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1795890438217888078-pkshatech-microsoft-copilot-for-microsoft-365-other-en-japan", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1798374461640442079-capita-group-github-copilot-professional-services-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1798509188103498351-softchoice-microsoft-copilot-for-microsoft-365-consumer-goods-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1800598946211744899-nflpa-azure-ai-services-nonprofit-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1802830664758543360-rti-international-microsoft-teams-nonprofit-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1804624062321190625-lotte-hotels-and-resorts-azure-ai-studio-travel-and-transportation-en-korea", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1812248324658189027-mcknight-microsoft-copilot-for-microsoft-365-nonprofit-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1812576965312816472-torfaen-microsoft-copilot-for-microsoft-365-national-government-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1813696493334607461-finastra-microsoft-copilot-for-microsoft-365-professional-services-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1820166640605522715-ouh-microsoft-365-copilot-health-provider-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1821284073143161043-insight-enterprises-inc-surface-laptop-professional-services-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1823424868741213189-syensqo-azure-open-ai-service-other-en-belgium", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1824902121184173261-british-heart-foundation-microsoft-copilot-nonprofit-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1825162116194410361-lgt-excel-banking-and-capital-markets-en-liechtenstein", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1825622008619351392-zshlavkova-microsoft-365-a3-primary-and-secondary-eduk-12-en-czechia", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1826307332667818248-farm-credit-canada-microsoft-365-copilot-government-en-canada", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1827391161519296074-orbitalwitness-azure-professional-services-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1827945851075596388-axon-azure-openai-service-national-government-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1828282129545930288-cdw-corporation-microsoft-viva-learning-consumer-goods-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1828290649088791526-virtualdentalcare-azure-virtual-machines-health-provider-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1832762432689198259-dlapiper-microsoft-365-copilot-professional-services-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1832767714677750676-cradle-azure-openai-service-other-unsegmented-en-malaysia", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1832880073951334987-jato-dynamics-azure-open-ai-service-automotive-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1833247205652391288-legrand-cloud-for-manufacturing-discrete-manufacturing-en-france", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1833614171187901763-sace-microsoft-viva-suite-insurance-en-italy", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1833973787621467669-doctolib-azure-openai-service-health-provider-en-france", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1834023197365666109-pimco-azure-ai-search-banking-and-capital-markets-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1834508996209335697-medigold-health-azure-ai-services-health-provider-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1834923084335117944-laliga-azure-arc-media-and-entertainment-en-spain", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1835026746816257326-harvey-azure-openai-service-other-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1835402038421112318-zurich-azure-openai-service-insurance-en-switzerland", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1835590701993611997-nba-azure-openai-service-media-and-entertainment-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1835832718338159187-mars-azure-machine-learning-professional-services-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1836108400811529412-airindia-azure-ai-search-travel-and-transportation-en-india", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1837247326532243131-canadian-tire-corporation-azure-retailers-en-canada", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1837367358659329204-hollandamerica-microsoft-dataverse-travel-and-transportation-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1837624667267994535-parloa-azure-openai-service-professional-services-en-germany", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1837633288515694884-eaton-microsoft-365-copilot-discrete-manufacturing-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1837667199713758792-clifford-chance-mcrosoft-365-copilot-professional-services-en-united-kingdom", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1837822642507786660-docusign-azure-logic-apps-other-en-united-states", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1837976425667863739-localiza-microsoft-365-copilot-automotive-en-brazil", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1838122771592262367-redcross-azure-ai-services-nonprofit-en-kenya", "source": "customers.microsoft.com"},
    {"url": "https://customers.microsoft.com/en-us/story/1838588977497742792-kmslh-azure-openai-service-professional-services-en-israel", "source": "customers.microsoft.com"},

    # Harvard Business Review - Subscriber only content
    #{"url": "https://hbr.org/2024/06/how-ai-can-make-make-us-better-leaders", "source": "hbr.org"},

    # Microsoft Info Pages - Ebook Download Link - Need registration
    #{"url": "https://info.microsoft.com/ww-landing-10-best-practices-to-accelerate-your-employees-ai-skills.html", "source": "info.microsoft.com"},
    #{"url": "https://info.microsoft.com/ww-landing-ai-strategy-roadmap-navigating-the-stages-of-ai-value-creation.html?lcid=EN-US", "source": "info.microsoft.com"},

    # Microsoft News
    {"url": "https://news.microsoft.com/2024/10/24/siemens-and-microsoft-scale-industrial-ai/", "source": "news.microsoft.com"},
    {"url": "https://news.microsoft.com/2024/11/14/accenture-microsoft-and-avanade-help-enterprises-reinvent-business-functions-and-industries-with-generative-ai-and-copilot/", "source": "news.microsoft.com"},
    {"url": "https://news.microsoft.com/source/asia/features/taiwan-hospital-deploys-ai-copilots-to-lighten-workloads-for-doctors-nurses-and-pharmacists/", "source": "news.microsoft.com"},
    {"url": "https://news.microsoft.com/source/emea/features/with-copilot-agents-pets-at-home-unleashes-an-ai-revolution/", "source": "news.microsoft.com"},
    {"url": "https://news.microsoft.com/source/features/ai/6-ai-trends-youll-see-more-of-in-2025/", "source": "news.microsoft.com"},
    {"url": "https://news.microsoft.com/source/features/digital-transformation/how-blackrocks-flight-crew-helped-copilot-for-microsoft-365-take-off/", "source": "news.microsoft.com"},
    {"url": "https://news.microsoft.com/source/features/innovation/a-conversation-with-kevin-scott-whats-next-in-ai/", "source": "news.microsoft.com"},
    {"url": "https://news.microsoft.com/en-au/features/anz-launches-first-of-its-kind-ai-immersion-centre-in-partnership-with-microsoft/"},
    {"url": "https://news.microsoft.com/it-it/2024/10/23/microsoft-ceo-satya-nadella-showcases-transformative-power-of-artificial-intelligence-for-italys-growth-at-microsoft-ai-tour-in-rome"},

    # Microsoft News PDFs / static resources - PDF is not a valid URL
    #{"url": "https://news.microsoft.com/source/wp-content/uploads/2023/11/US51315823-IG-ADA.pdf", "source": "news.microsoft.com/pdf"},

    # Nuance Newsroom
    {"url": "https://news.nuance.com/2024-03-08-Providence-and-Microsoft-Enable-AI-Innovation-at-Scale-to-Improve-the-Future-of-Care", "source": "news.nuance.com"},

    # Microsoft Query API (static files / assets) - Redirects to PDFs
    #{"url": "https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RW1cZ7v?wt.mc_id=esi_lfo_content_wwl", "source": "cms.rt.microsoft.com"},
    #{"url": "https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RW1jMq4", "source": "cms.rt.microsoft.com"},

    # Tech Community Blog
    {"url": "https://techcommunity.microsoft.com/blog/vivasales-blog/how-netlogic-computer-consulting-is-boosting-its-sales-performance-with-microsof/3831750", "source": "techcommunity.microsoft.com"},

    # Microsoft Videos - No text here
    # {"url": "https://videos.microsoft.com/infrastructure-for-the-era-of-ai/watch/4xWafUAXA2L8mJGhx6Pbeq", "source": "videos.microsoft.com"},
    # {"url": "https://videos.microsoft.com/infrastructure-for-the-era-of-ai/watch/AQC5ifDQZ5nHerg7WxQibe", "source": "videos.microsoft.com"},
    # {"url": "https://videos.microsoft.com/infrastructure-for-the-era-of-ai/watch/aCiVYwQmXeM5KNSRe4eF1i", "source": "videos.microsoft.com"},
    # {"url": "https://videos.microsoft.com/infrastructure-for-the-era-of-ai/watch/d6kVi5ThXLQ4raJui47pob", "source": "videos.microsoft.com"},
    # {"url": "https://videos.microsoft.com/infrastructure-for-the-era-of-ai/watch/qmuNEehwJ9p2UNNwP9AH54", "source": "videos.microsoft.com"},
    # {"url": "https://videos.microsoft.com/infrastructure-for-the-era-of-ai/watch/zi9ic8t9Fk9o7rZyFgssE9", "source": "videos.microsoft.com"},

    # Fast Company
    {"url": "https://www.fastcompany.com/91254572/why-ai-and-skills-are-the-new-barometer-for-organizational-success", "source": "fastcompany.com"},

    # LinkedIn
    {"url": "https://www.linkedin.com/business/talent/blog/learning-and-development/generative-ai-impact-on-learning-and-development", "source": "linkedin.com"},
    {"url": "https://www.linkedin.com/business/talent/blog/learning-and-development/new-framework-for-ai-upskilling", "source": "linkedin.com"},
    {"url": "https://www.linkedin.com/pulse/can-ai-help-jared-spataro-f5esc/", "source": "linkedin.com"},
    {"url": "https://www.linkedin.com/pulse/when-comes-ai-its-system-model-matters-jared-spataro-l90jc/", "source": "linkedin.com"},
    {"url": "https://www.linkedin.com/pulse/why-leaders-cant-ignore-human-energy-crisis-kathleen-hogan/", "source": "linkedin.com"},
    {"url": "https://www.linkedin.com/pulse/work-ai-like-its-colleague-calculator-jared-spataro-acghc/", "source": "linkedin.com"},

    # McKinsey - Need to accept all cookies
    #{"url": "https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-state-of-ai?cid=soc-web", "source": "mckinsey.com"},

    # Microsoft Cloud Blog - Special Interactive Must Wait 
    #{"url": "https://www.microsoft.com/en-us/microsoft-cloud/blog/2024/10/17/colombia-and-brazil-embrace-the-potential-of-cloud-and-ai-solutions-to-drive-growth-and-tackle-social-challenges/", "source": "microsoft.com/microsoft-cloud/blog"},

    # Microsoft Research
    {"url": "https://www.microsoft.com/en-us/research/blog/ai4science-to-empower-the-fifth-paradigm-of-scientific-discovery/", "source": "microsoft.com/research"},
    # Directory page not a endpage {"url": "https://www.microsoft.com/en-us/research/group/ai-for-good-research-lab/", "source": "microsoft.com/research"},
    #- Video no text {"url": "https://www.microsoft.com/en-us/research/video/at-the-frontiers-of-science-exciting-advances-in-protein-design/", "source": "microsoft.com/research"},

    # Microsoft WorkLab
    {"url": "https://www.microsoft.com/en-us/worklab/11-unexpected-ai-at-work-insights-from-2024", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/3-proven-ways-to-make-ai-usage-stick", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/5-key-principles-for-implementing-an-ai-strategy-across-your-organization", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/5-new-habits-will-help-you-get-the-most-out-of-ai-in-2024", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/a-role-model-for-ai-driven-transformation", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-a-whole-new-way-of-working", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-at-work-3-scenarios-for-unlocking-the-full-potential-of-ai", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-at-work-can-ai-help-with-this", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-at-work-in-2025-ai-will-help-us-navigate-uncertainty", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-at-work-what-are-agents-how-do-they-help-businesses", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-at-work-why-cios-matter-more-than-ever", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-data-drop-5-copilot-prompts-to-try-out-at-work", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-data-drop-how-ai-breaks-down-barriers-to-inclusivity", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-data-drop-the-11-by-11-tipping-point", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-data-drop-what-the-future-workforce-really-cares-about", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-data-drop-which-jobs-have-an-ai-advantage", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-impact-at-3-industry-leading-companies", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-impact-at-dow-copilot-identifies-millions-in-cost-savings", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/ai-is-already-changing-work-microsoft-included", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/anatomy-of-a-copilot", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/dayana-falcon-espn-talent-mobility-manager-shares-her-moden-work-essentials", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/enlist-ai-in-your-fight-against-email-overload", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/how-6-experts-use-next-generation-ai", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/how-ai-gives-you-data-synthesis-superpowers", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/how-business-leaders-are-using-copilot-right-now", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/how-copilot-turns-everyone-into-a-manager", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/how-i-prompt-leaders-share-their-favorite-ai-time-savers", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/how-we-measure-the-value-of-ai-at-work", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/inside-ai-native-ad-agency", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/learn-from-ai-native-firms-or-get-left-behind", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/llms-are-becoming-a-commodity-now-what", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/our-year-with-copilot-what-microsoft-has-learned-about-ai-at-work", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/the-art-and-science-of-working-with-ai", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/the-key-ingredient-in-every-copilot-conversation", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/the-key-to-a-thriving-workforce-is-a-smart-approach-to-ai", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/the-ripple-effect-of-ai-at-work", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/there-are-no-shortcuts-to-high-performance", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/to-build-ai-into-your-habits-picture-a-pyramid", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/what-can-ai-native-startups-teach-the-rest-of-us", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/what-new-terms-like-goblin-mode-reveal-about-work-in-2023", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/what-we-mean-when-we-say-ai-is-usefully-wrong", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/when-it-comes-to-ai-do-not-build-islands-of-intelligence", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/why-using-a-polite-tone-with-ai-matters", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/with-copilot-every-meeting-is-a-digital-artifact", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/work-trend-index/ai-at-work-is-here-now-comes-the-hard-part", "source": "microsoft.com/worklab"},
    {"url": "https://www.microsoft.com/en-us/worklab/work-with-ai-like-its-a-colleague-not-a-calculator", "source": "microsoft.com/worklab"},

    # Microsoft WorkLab Podcasts
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/all-leaders-can-learn-from-how-ai-is-revolutionizing-medicine", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/an-ai-first-data-scientist-on-current-limits-and-future-potential-of-ai", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/are-managers-the-key-to-unlocking-the-true-potential-of-ai", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/charles-duhigg-on-how-to-build-new-habits-for-the-ai-era", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/charles-lamanna-on-the-next-big-role-for-ai", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/conor-grennan-on-moving-beyond-the-search-engine-mindset", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/eric-horvitz-on-the-possibilities-of-generative-ai-for-human-thriving", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/futurist-amy-webb-on-the-most-plausible-outcomes-for-ai-and-work", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/harvard-business-schools-christina-wallace-on-how-ai-can-help-us-rebalance-our-lives", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/how-ai-can-reveal-the-neural-secrets-behind-great-leadership", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/how-can-leaders-invest-the-time-that-ai-gives-back", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/how-copilot-is-transforming-one-global-creative-agency", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/how-do-you-solve-a-problem-thats-never-been-solved-before", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/how-leaders-will-use-ai-to-unleash-creativity", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/how-to-become-an-ai-powered-organization", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/inside-accentures-ai-journey-with-ceo-julie-sweet", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/jenny-lay-flurrie-on-why-inclusivity-benefits-everyone", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/linkedin-vp-aneesh-raman-on-why-adaptability-is-the-skill-of-the-moment", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/lumen-ceo-kate-johnson-says-leaders-should-be-catalysts", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/microsoft-chief-scientist-on-ai-untapped-potential", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/microsoft-deputy-cto-sam-schillace-on-how-ai-will-shift-our-productivity-paradigm", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/nir-eyal-on-how-to-defeat-distraction-in-an-always-on-world", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/regain-control-of-your-focus-and-attention-with-researcher-gloria-mark", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/season-5-will-explore-how-to-tap-the-full-potential-of-ai", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/stanford-professor-erik-brynjolfsson-on-how-ai-will-transform-productivity", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/tackling-worlds-toughest-problems-with-ai", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/timm-chiusano-on-ai-and-winning-the-week", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/want-real-ai-transformation-focus-on-people-and-processes", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/wharton-professor-ethan-mollick-on-the-urgency-of-getting-in-front-of-ai", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/why-youre-overwhelmed-at-work", "source": "microsoft.com/worklab/podcast"},
    {"url": "https://www.microsoft.com/en-us/worklab/podcast/will-ai-make-work-more-human", "source": "microsoft.com/worklab/podcast"}

    # Washington Post - Podcasts only no transcripts
    #{"url": "https://www.washingtonpost.com/washington-post-live/2024/03/28/how-technology-is-transforming-collaboration-innovation-work/", "source": "washingtonpost.com"},

    # YouTube - Use different scraper
    # {"url": "https://www.youtube.com/watch?v=9fEgd6WDP2w", "source": "youtube.com"},
    # {"url": "https://youtu.be/Iqzqp69QCKI?si=wN9v8MyFvGYnbllC", "source": "youtube.com"},
    # {"url": "https://youtu.be/kOkDTvsUuWA?si=oko2zGEJ-XEh9K1l", "source": "youtube.com"},
    # {"url": "https://youtube.com/playlist?list=PLFPUGjQjckXHW1Zg8D6veiY6kg6WjL8EC&si=Bpg8jt0KzJoeJcmS", "source": "youtube.com"},
    # {"url": "https://youtube.com/playlist?list=PLFPUGjQjckXHW1Zg8D6veiY6kg6WjL8EC&si=bG9HchZtXp6yV94t", "source": "youtube.com"},
    # {"url": "https://youtube.com/playlist?list=PLFPUGjQjckXHW1Zg8D6veiY6kg6WjL8EC&si=xUznDJuZtUIM92bF", "source": "youtube.com"},

]